name: antlr_parser
description: A sample dart package from the template.
version: 0.0.1
repository: https://github.com/DrafaKiller/ANTRLParser-dart

publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  token_parser: ^1.6.0

dev_dependencies:
  lints: ^2.0.0
